export const tokenList = [
    {
        name: 'Binance',
        symbol: 'BNB',
        image: 'https://content-api.changenow.io/uploads/bnbbsc_331e969a6b.svg',
        decimals: 18,
        convertId: 1839,
    },
    {
        name: 'Ethereum',
        symbol: 'ETH',
        image: 'https://content-api.changenow.io/uploads/eth_f4ebb54ec0.svg',
        decimals: 6,
        convertId: 1027,
    },
    {
        name: 'Tether',
        symbol: 'USDT',
        image: 'https://content-api.changenow.io/uploads/usdterc20_01c09cad36.svg',
        decimals: 6,
        convertId: 825,
    },
    {
        name: 'USDC coin',
        symbol: 'USDC',
        image: 'https://content-api.changenow.io/uploads/usdcerc20_acd5759c8c.svg',
        decimals: 6,
        convertId: 3408,
    },
    {
        name: 'Dai',
        symbol: 'DAI',
        image: 'https://content-api.changenow.io/uploads/dai_5315155551.svg',
        decimals: 18,
        convertId: 4943,
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        image: 'https://content-api.changenow.io/uploads/btc_d8db07f87d.svg',
        decimals: 8,
        convertId: 1,
    },
    {
        name: 'Litecoin',
        symbol: 'LTC',
        image: 'https://content-api.changenow.io/uploads/ltc_a399d6378f.svg',
        decimals: 8,
        convertId: 2,
    },
    {
        name: 'Solana',
        symbol: 'SOL',
        image: 'https://content-api.changenow.io/uploads/sol_3b3f795997.svg',
        decimals: 9,
        convertId: 5426,
    },
    {
        name: 'Tron',
        symbol: 'TRX',
        image: 'https://content-api.changenow.io/uploads/trx_f14430166e.svg',
        decimals: 6,
        convertId: 1958,
    },
    {
        name: 'Stellar',
        symbol: 'XLM',
        image: 'https://content-api.changenow.io/uploads/xlm_8ef7a0cde8.svg',
        decimals: 7,
        convertId: 512,
    },
    {
        name: 'Dogecoin',
        symbol: 'DOGE',
        image: 'https://content-api.changenow.io/uploads/doge_a0321dc732.svg',
        decimals: 8,
        convertId: 74,
    },
    {
        name: 'Polkadot',
        symbol: 'DOT',
        image: 'https://content-api.changenow.io/uploads/dot_c006c687e7.svg',
        decimals: 12,
        convertId: 6636,
    },
    {
        name: 'Thorchain',
        symbol: 'RUNE',
        image: 'https://content-api.changenow.io/uploads/rune_4c80e5a764.svg',
        decimals: 6,
        convertId: 4157,
    },
    {
        name: 'EOS EVM',
        symbol: 'EOS',
        image: 'https://content-api.changenow.io/uploads/eosbsc_f766b7e89b.svg',
        decimals: 18,
        convertId: 1765,
    },
    {
        name: 'Algorand',
        symbol: 'ALGO',
        image: 'https://content-api.changenow.io/uploads/algo_5f31b4a13e.svg',
        decimals: 6,
        convertId: 4030,
    },
    {
        name: 'Avalanche',
        symbol: 'AVAX',
        image: 'https://content-api.changenow.io/uploads/avaxs_470dc56248.svg',
        decimals: 18,
        convertId: 5805,
    },
    {
        name: 'Polygon',
        symbol: 'MATIC',
        image: 'https://content-api.changenow.io/uploads/matic_token_f9906e3f5d.svg',
        decimals: 18,
        convertId: 3890,
    },
    {
        name: 'Pepe',
        symbol: 'PEPE',
        image: 'https://cryptologos.cc/logos/pepe-pepe-logo.png?v=035',
        decimals: 18,
        convertId: 24478,
    },
    {
        name: 'Monero',
        symbol: 'XMR',
        image: 'https://cryptologos.cc/logos/monero-xmr-logo.png?v=035',
        decimals: 18,
        convertId: 328,
    },
     {
        name: 'Wrapped Monero',
        symbol: 'WXMR',
        image: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8235.png',
        decimals: 18,
        convertId: 8235,
    },
    {
        name: 'Toncoin',
        symbol: 'TON',
        image: 'https://cryptologos.cc/logos/toncoin-ton-logo.png?v=035',
        decimals: 18,
        convertId: 11419,
    },
    {
        name: 'Chainlink',
        symbol: 'LINK',
        image: 'https://cryptologos.cc/logos/chainlink-link-logo.png?v=035',
        decimals: 18,
        convertId: 1975,
    },
    {
        name: 'Bitcoin Cash',
        symbol: 'BCH',
        image: 'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png?v=035',
        decimals: 18,
        convertId: 1831,
    },
    {
        name: 'Token',
        symbol: 'TOKEN',
        image: 'https://s2.coinmarketcap.com/static/img/coins/64x64/28299.png',
        decimals: 18,
        convertId: 28299,
    },
    {
        name: 'Zcash',
        symbol: 'ZEC',
        image: 'https://cryptologos.cc/logos/zcash-zec-logo.png?v=035',
        decimals: 18,
        convertId: 1437,
    },
    {
        name: 'Cardano',
        symbol: 'ADA',
        image: 'https://cryptologos.cc/logos/cardano-ada-logo.png?v=035',
        decimals: 6,
        convertId: 2010,
    },
    {
        name: 'MainnetZ',
        symbol: 'NetZ',
        image: 'https://s2.coinmarketcap.com/static/img/coins/64x64/28659.png',
        decimals: 9,
        convertId: 28659,
    },
];
